#!/bin/bash

# color based on catppuccin
options=(
	style=round
	width=6.0
	hidpi=off
	active_color=0xfff38ba8
	inactive_color=0xff585b70
	background_color=0xff1e1e2e
	blacklist="Loop"
)

borders "${options[@]}"