#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors

ITEM_DIR="$HOME/.config/sketchybar/items"     # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/scripts" # Directory where all the plugin scripts are stored

FONT="JetBrainsMono Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDING=10                    # All paddings use this value (icon, label, background)
HEIGHT=30

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER >/dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
	height=$HEIGHT
	color=${ALPHA_BAR}${BASE}
	position=bottom
	sticky=on
	padding_right=0
	padding_left=0
	y_offset=5
	margin=10
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
	updates=when_shown

	padding_right=$PADDING
	padding_left=$PADDING

	icon.font="$FONT:Bold:12.0"
	icon.color=${ALPHA_ITEM}${TEXT}
	icon.padding_right=5

	label=""
	label.font="$FONT:Semibold:12.0"
	label.color=${ALPHA_ITEM}${TEXT}

	popup.background.border_width=2
	popup.background.corner_radius=10
	popup.background.border_color=0x7f${SURFACE2}
	popup.background.color=${ALPHA_ITEM}${BASE}
	popup.background.shadow.drawing=on
	popup.y_offset=-5

	shadow=on
)

sketchybar --default "${defaults[@]}"

bracket=(
 	background.color=${ALPHA_ITEM}${BASE}
	background.height=$HEIGHT
	background.corner_radius=10
	background.border_color=0x7f${SURFACE2}
	background.border_width=2
)

pill=(
 	background.color=${ALPHA_ITEM}${BASE}
	background.height=$HEIGHT
	background.corner_radius=10
	background.border_color=0x7f${SURFACE2}
	background.border_width=2
	label.padding_right=$PADDING
	icon.padding_left=$PADDING
	padding_right=0
	padding_left=0
)

spacer=(
	background.drawing=off
	label.drawing=off
	icon.drawing=off
	width=10
)

# Left

source "$ITEM_DIR/space.sh"

sketchybar --add bracket bracket_spaces '/space\..*/' \
		   --set bracket_spaces "${bracket[@]}"

sketchybar --add item spacer_left1 left \
		   --set spacer_left1 "${spacer[@]}"

source "$ITEM_DIR/front_app.sh"
sketchybar --set front_app "${pill[@]}"

sketchybar --add item spacer_left2 left \
		   --set spacer_left2 "${spacer[@]}"

source "$ITEM_DIR/media.sh"
sketchybar --set media "${pill[@]}"

# Right

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"

sketchybar --set clock padding_left=0

sketchybar --add bracket bracket_time clock calendar \
           --set bracket_time "${bracket[@]}"

sketchybar --add item spacer_right1 right \
		   --set spacer_right1 "${spacer[@]}"

source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/brew.sh"

sketchybar --set battery padding_left=0
sketchybar --set volume padding_left=0

sketchybar --add bracket bracket_status battery volume brew \
           --set bracket_status "${bracket[@]}"

sketchybar --add item spacer_right2 right \
		   --set spacer_right2 "${spacer[@]}"

source "$ITEM_DIR/sys.sh"

sketchybar --set cpu padding_left=0
sketchybar --set ram padding_left=0

sketchybar --add bracket bracket_sys cpu ram disk \
           --set bracket_sys "${bracket[@]}"

sketchybar --add item spacer_right3 right \
		   --set spacer_right3 "${spacer[@]}"

source "$ITEM_DIR/weather.sh"
sketchybar --set weather "${pill[@]}"

sketchybar --add item spacer_right4 right \
		   --set spacer_right4 "${spacer[@]}"

source "$ITEM_DIR/prayer.sh"
sketchybar --set prayer "${pill[@]}"

# sketchybar --add item spacer_right5 right \
# 		   --set spacer_right5 "${spacer[@]}"

# source "$ITEM_DIR/finance.sh"
# sketchybar --set finance "${pill[@]}"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update