# ──────────────────────────────
# TAPS
# ──────────────────────────────
tap "felixkratz/formulae"
tap "jesseduffield/lazydocker"
tap "koekeishiya/formulae"

# ──────────────────────────────
# BREWS
# ──────────────────────────────

## Core Tools (native alternatives)
brew "bat"      # cat
brew "btop"     # htop
brew "eza"      # ls
brew "gping"    # ping
brew "tlrc"     # man

## Development
brew "colima"
brew "d2"
brew "docker"
brew "lazydocker"
brew "minikube"
brew "mise"
brew "neovim"

## Tools
brew "cointop"
brew "scrcpy"
brew "netcat"
brew "chafa"

## Customization
brew "chezmoi"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"

## Terminal
brew "antidote"
brew "fzf"
brew "oh-my-posh"
brew "grc"

# ──────────────────────────────
# CASKS
# ──────────────────────────────

## Development
cask "android-platform-tools"
cask "antigravity"
cask "gcloud-cli"
cask "ghostty"
cask "orbstack"
cask "warp"

## Fonts
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"

## Messaging
cask "telegram"
cask "whatsapp"

## Media
cask "stremio"
cask "tidal"
cask "vlc"

## Customization
cask "alt-tab"
cask "loop"
cask "raycast"
cask "shottr"
cask "unnaturalscrollwheels"

## Tools
cask "chatgpt"
cask "jdownloader"
cask "the-unarchiver"
cask "utm"

## Other
cask "vivaldi"
